/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasrumah2;

/**
 *
 * @author Nanta
 */
public class tgsrmh extends javax.swing.JFrame {

    /**
     * Creates new form tgsrmh
     */
    public tgsrmh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        HB1 = new javax.swing.JTextField();
        HB2 = new javax.swing.JTextField();
        HB3 = new javax.swing.JTextField();
        DISKON = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Harga Barang 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 50, 100, 14);

        jLabel2.setText("Harga Barang 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 90, 100, 14);

        jLabel3.setText("Harga Barang 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 130, 100, 14);

        jLabel4.setText("Diskon");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 170, 100, 14);

        jButton1.setText("PROSES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 200, 120, 23);
        getContentPane().add(HB1);
        HB1.setBounds(240, 40, 200, 30);
        getContentPane().add(HB2);
        HB2.setBounds(240, 80, 200, 30);
        getContentPane().add(HB3);
        HB3.setBounds(240, 120, 200, 30);

        DISKON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISKONActionPerformed(evt);
            }
        });
        getContentPane().add(DISKON);
        DISKON.setBounds(240, 160, 200, 30);

        Hasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Hasil);
        Hasil.setBounds(120, 260, 350, 130);

        setBounds(0, 0, 620, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void DISKONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISKONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DISKONActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int hb1 = Integer.parseInt(HB1.getText());
        int hb2 = Integer.parseInt(HB2.getText());
        int hb3 = Integer.parseInt(HB3.getText());
        int diskon = Integer.parseInt(DISKON.getText());
        
        int diskon1 = (hb1+hb2+hb3)*diskon / 100;
        int total = hb1 + hb2 + hb3;
        int hasil2 = (hb1 + hb2 + hb3)-diskon1;
        
        
        
        Hasil.setText("HARGA BARANG 1 = "+hb1+"\n"+ "HARGA BARANG 2 = "+hb2+"\n"+" HARGA BARANG 3 = "+hb3+"\n"+" DISKON = "+diskon+"\n"+" TOTAL BAYAR = "+total+"\n"+" Jumlah Bayar = "+hasil2);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tgsrmh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tgsrmh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tgsrmh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tgsrmh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tgsrmh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DISKON;
    private javax.swing.JTextField HB1;
    private javax.swing.JTextField HB2;
    private javax.swing.JTextField HB3;
    private javax.swing.JTextField Hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
